SET IDENTITY_INSERT [dbo].[Natives] ON;

MERGE INTO [dbo].[Natives] AS Target
USING (VALUES
    (1, 'Akola'),
    (2, 'Amet'),
    (3, 'Asind'),
    (4, 'Bagana'),
    (5, 'Baggad'),
    (6, 'Bagoliya'),
    (7, 'Bambora'),
    (8, 'Barar'),
    (9, 'Bemali'),
    (10, 'Bhagwanpura'),
    (11, 'Bhilwara'),
    (12, 'Bhim'),
    (13, 'Bhitanagar'),
    (14, 'Chapli'),
    (15, 'Chileshwar'),
    (16, 'Chitamba'),
    (17, 'Choti Sadadi'),
    (18, 'Deogarh'),
    (19, 'Devariya'),
    (20, 'Dolpura'),
    (21, 'Dungla'),
    (22, 'Gangapur'),
    (23, 'Geradiya'),
    (24, 'Godas'),
    (25, 'Gogathala'),
    (26, 'Gyangarh'),
    (27, 'Isharmand'),
    (28, 'Jadol'),
    (29, 'Kaladeh'),
    (30, 'Kalesariya'),
    (31, 'Kaliyas'),
    (32, 'Kameri'),
    (33, 'Kankroli'),
    (34, 'Kanod'),
    (35, 'Kareda'),
    (36, 'Katar'),
    (37, 'Kesunda'),
    (38, 'Khajuriya'),
    (39, 'Kharnota'),
    (40, 'Khemana'),
    (41, 'Kidimal'),
    (42, 'Koshithal'),
    (43, 'Kukarkheda'),
    (44, 'Kundva'),
    (45, 'Kuvathal'),
    (46, 'Lasani'),
    (47, 'Lasdavan'),
    (48, 'Madariya'),
    (49, 'Mokhunda'),
    (50, 'Narana'),
    (51, 'Nathadiyas'),
    (52, 'Negadiya Ka Kheda'),
    (53, 'Nimbaheda'),
    (54, 'Nimbaheda Jatan'),
    (55, 'Pipalinagar'),
    (56, 'Pithas'),
    (57, 'Potlan'),
    (58, 'R.D. Mines'),
    (59, 'Raipur'),
    (60, 'Revada'),
    (61, 'Sameliya'),
    (62, 'Sangawas'),
    (63, 'Sarewadi'),
    (64, 'Shivpur'),
    (65, 'Tal'),
    (66, 'Thana'),
    (67, 'Thikarvas'),
    (68, 'Todgarh'),
    (69, 'Udaipur'),
    (70, 'Ullalai'),
    (71, 'Umari')
)
AS Source ([Id], [Name])
ON Target.[Id] = Source.[Id]
WHEN NOT MATCHED BY TARGET THEN
    INSERT ([Id], [Name])
    VALUES (Source.[Id], Source.[Name]);

SET IDENTITY_INSERT [dbo].[Natives] OFF;